server:
  port: 5000 # AWS Elastic Beanstalk (for some reason) expects to listen for requests on port 5000
  servlet:
    context-path: /quizzard

spring:
  application:
    name: quizzard-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://java-react-enterprise-211101.c0nbqj7oncuf.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=quizzard
    username: postgres
    password: revature
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include:
          - "beans"
          - "health"
          - "info"